### ISSUE TITLE
Version 1.0.0 still using the 0.9.2 firmware

### ISSUE THREAD

**Issue by murad-alm** [elral/MF_FCU_EFIS_OLEDs#15]
Hello,
version 1.0.0 is still searching for the firmware version 0.9.2 as shown in the screenshot below:

![image](https://github.com/user-attachments/assets/772babf6-8001-45e1-925f-e653c7eb8d07)

**Comment by elral** [comment]
Uuups, thanks for reporting.
I will make a new release with the changed board.json files.

"LatestFirmwareVersion": "0.9.2" wasn't changed to "1.0.0"

**Comment by murad-alm** [comment]
"elral_gagagu_fcu_efis_mega_1_0_0" should be renamed to "gagagu_fcu_efis_mega_1_0_0" too (or the other way around in the config file)

**Comment by murad-alm** [comment]
PR is ready, ty for the help!
https://github.com/elral/MF_FCU_EFIS_OLEDs/pull/17
