### ISSUE TITLE
avrdude timed out while flashing the firmware

### ISSUE THREAD

**Issue by murad-alm** [elral/MF_FCU_EFIS_OLEDs#16]
Hello,
I'm getting a timeout error while flashing the firmware on an Arduino Mega 2560.
I've tried the EEPROM clear sketch in Arduino IDE to clear but it didn't help.
Edit: Version 0.9.2 

Error:
`MobiFlightFirmwareUpdater.RunAvrDude(): avrdude timed out! Something went wrong when flashing with command 
 C:\Users\###\AppData\Local\MobiFlight\MobiFlight Connector\Arduino\hardware\tools\avr\bin\avrdude -C"C:\Users\###\AppData\Local\MobiFlight\MobiFlight Connector\Arduino\hardware\tools\avr\etc\avrdude.conf" -patmega2560 -cwiring -PCOM6 -b115200 -D -Uflash:w:"C:\Users\###\AppData\Local\MobiFlight\MobiFlight Connector\Community\Elral_FCU_EFIS\firmware\gagagu_fcu_efis_mega_0_9_2.hex":i.
`

![image](https://github.com/user-attachments/assets/b5715aac-5073-4ba3-875e-8f9e7d685aa2)

![image](https://github.com/user-attachments/assets/af3d750d-5f5e-4f31-9a89-58e3d0888440)

**Comment by elral** [comment]
Hello @murad-alm 
the firmware is getting flashed, the Error comes during verifying the FW. After a restart of the connector the board should work.

To avoid this, could you please change the TimeoutForFirmwareUpdate value in the gagagu_fcu_efis_mega.board.json file from 25000 to 30000. This file is in the folder ./Community/Elral/boards/.
Please report if this works.
Thanks and regards
Ralf

**Comment by murad-alm** [comment]
> Hello @murad-alm the firmware is getting flashed, the Error comes during verifying the FW. After a restart of the connector the board should work.
> 
> To avoid this, could you please change the TimeoutForFirmwareUpdate value in the gagagu_fcu_efis_mega.board.json file from 25000 to 30000. This file is in the folder ./Community/Elral/boards/. Please report if this works. Thanks and regards Ralf

Hi Ralf,
i really appreciate your rapid feedback!!
I will test your suggested solution and will report the results!

**Comment by murad-alm** [comment]
> Hello @murad-alm the firmware is getting flashed, the Error comes during verifying the FW. After a restart of the connector the board should work.
> 
> To avoid this, could you please change the TimeoutForFirmwareUpdate value in the gagagu_fcu_efis_mega.board.json file from 25000 to 30000. This file is in the folder ./Community/Elral/boards/. Please report if this works. Thanks and regards Ralf

Can't do, because the https://github.com/elral/MF_FCU_EFIS_OLEDs/issues/15 is blocking (I'm still using 0.9.2 because of the reported typo).

Will wait for your update :)

**Comment by elral** [comment]
Change "LatestFirmwareVersion": "0.9.2" to "1.0.0" within the gagagu_fcu_efis_mega.board.json file. Then it should work.

**Comment by murad-alm** [comment]
PR is ready, ty for the help!
https://github.com/elral/MF_FCU_EFIS_OLEDs/pull/17

**Comment by murad-alm** [comment]
@elral  just one last question please. I'm not very experienced with Arduino/Mobiflight.
Readme says  "_Set the I2C adress to 0x70/0x71 or to the adress you have choosen on the portexpander_"

Could you please elaborate on this? What kind of address is it please? any links/references are very appreciated!

**Comment by elral** [comment]
It's the address of the TCA9548, shown in the wiring diagram on the very left side. If you do not connect anything to A0/A1/A2 the port expander uses it's base address 0x70. Setting A0 to GND is the next address 0x71 and so on.

**Comment by murad-alm** [comment]
> It's the address of the TCA9548, shown in the wiring diagram on the very left side. If you do not connect anything to A0/A1/A2 the port expander uses it's base address 0x70. Setting A0 to GND is the next address 0x71 and so on.

my displays are finally showing signs of life. I appreciate your kind help!!

Have a nice weekend!

**Comment by elral** [comment]
Great to hear this!
Wish you also a nice weekend and success with your project and MobiFlight.
