### ISSUE TITLE
ssd1306 support

### ISSUE THREAD

**Issue by chegevarko1982** [elral/MF_FCU_EFIS_OLEDs#2]
I would like to be able to assemble a circuit using only ssd1306 disp, I think it would not be difficult to add as an option in the code.
All the best, thanks for your work

**Comment by 001000010** [comment]
That's the same topic we run in like for the OLED for GNC255 where two different driver should be supported.

There is no real decision how to handle tjis, but oin contrast to the GNC255 these OLED's are unsing I2C.

I will add a check what I2C adress for the port expander is defined in the connector. If the adress is 0x70, than diplays with SH1106 driver are supported. If the adress is set to `0x71` displays with SSD1306 driver are supported. In this case a jumper on the I2C port expander has to be soldered to set adress `0x71` .

I assume that all OLED displays have the same I2C adress of `0x3C`, not sure if there are display out with other adresses.

**Comment by elral** [comment]
@chegevarko1982 Could you please test the latest version 0.9.0?
By choosing the I2C address you can define the driver for the display (see Readme)

**Comment by elral** [comment]
Fixed by PR #3
